name: brave_girls
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.1+7

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.1.4
  firebase_auth: ^3.1.3
  cloud_firestore: ^2.5.3
  fimber: ^0.6.1
  flutter_phoenix: ^1.0.0
  http: ^0.13.0
  url_launcher: ^6.0.2
  cached_network_image: ^3.0.0
  web_scraper: ^0.1.4
  photo_view: ^0.13.0
  image_gallery_saver: ^1.6.9
  permission_handler: ^8.1.6
  dio: ^4.0.0-prev3
  fluttertoast: ^8.0.3
  flutter_native_splash: ^1.1.5+1
  flutter_launcher_icons: ^0.9.0
  dartx: ^0.7.1
  youtube_player_flutter: ^8.0.0
  supabase: ^0.2.7
  table_calendar: ^3.0.2
  intl: ^0.17.0
  webview_flutter: ^2.0.4
  glassmorphism: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/launcher_icon.png"
  image_path_android: "assets/images/launcher_icon.png"

flutter:

  uses-material-design: true

  assets:
   - assets/images/

  fonts:
   - family: NotoSansKR Bold
     fonts:
       - asset: assets/fonts/NotoSansKR-Bold.otf

   - family: NotoSansKR Light
     fonts:
       - asset: assets/fonts/NotoSansKR-Light.otf

   - family: NotoSansKR Regular
     fonts:
       - asset: assets/fonts/NotoSansKR-Regular.otf

   - family: NotoSansKR Medium
     fonts:
       - asset: assets/fonts/NotoSansKR-Medium.otf

flutter_native_splash:
  color: "#333456"
