name: brave_girls
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.0.0-nullsafety.2
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1
  fimber: ^0.6.1
  flutter_phoenix: ^1.0.0
  http: ^0.13.0
  url_launcher: ^6.0.2
  cached_network_image: ^3.0.0-nullsafety
  web_scraper: ^0.1.4
  photo_view: ^0.11.1
  image_gallery_saver:
    git:
      url: https://github.com/fzyzcjy/image_gallery_saver.git
      ref: master
  permission_handler: ^6.1.1
  dio: ^4.0.0-prev3
  fluttertoast: ^8.0.3
  flutter_native_splash: ^1.1.5+1
  flutter_launcher_icons: ^0.9.0
  dartx: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/launcher_icon.png"
  image_path_android: "assets/images/launcher_icon.png"

flutter:

  uses-material-design: true

  assets:
   - assets/images/

  fonts:
   - family: NotoSansKR Bold
     fonts:
       - asset: assets/fonts/NotoSansKR-Bold.otf

   - family: NotoSansKR Light
     fonts:
       - asset: assets/fonts/NotoSansKR-Light.otf

   - family: NotoSansKR Regular
     fonts:
       - asset: assets/fonts/NotoSansKR-Regular.otf

   - family: NotoSansKR Medium
     fonts:
       - asset: assets/fonts/NotoSansKR-Medium.otf

flutter_native_splash:
  color: "#333456"
